/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const PortfolioItem = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});
export const Service = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'iconName' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'clientName' : IDL.Text,
  'role' : IDL.Text,
  'quote' : IDL.Text,
  'company' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getPortfolio' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'getPortfolioByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PortfolioItem)],
      ['query'],
    ),
  'getPortfolioTitles' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getServiceByTitle' : IDL.Func([IDL.Text], [Service], ['query']),
  'getServiceTitles' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getTestimonialCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const PortfolioItem = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  const Service = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'iconName' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'clientName' : IDL.Text,
    'role' : IDL.Text,
    'quote' : IDL.Text,
    'company' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getPortfolio' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
    'getPortfolioByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PortfolioItem)],
        ['query'],
      ),
    'getPortfolioTitles' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getServiceByTitle' : IDL.Func([IDL.Text], [Service], ['query']),
    'getServiceTitles' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getTestimonialCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };